# Site settings
title: IKATS
email: contact@ikats.org

description: >  # This means to ignore newlines until "baseurl:"
  IKATS is an innovative toolkit for analysing time series.

# The subpath of your site, e.g. /blog/
baseurl: ""
# The base hostname & protocol for your site without a trailing slash.
url: "https://www.ikats.org"

# http://jekyllrb.com/docs/permalinks/
permalink: date

plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
highlighter: rouge

exclude:
  - bin
  - CONTRIBUTING.website.md
  - INSTALL.md
  - README.md
  - assets
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Configurable links (redirections)
links:
  tech-doc-archi: '404'
  tech-doc-api: '404'
  wiki: 'https://github.com/IKATS/IKATS/wiki'
  organisation: 'https://github.com/IKATS'
  sources: 'https://github.com/IKATS'
  issues: 'https://github.com/IKATS/IKATS/issues'
  sandbox: 'https://github.com/IKATS/ikats-sandbox'
